version: '3.8'
services:
  app:
    build:
      context: .
      target: dev
      dockerfile: Dockerfile
    tty: true
    container_name: eks-api
    volumes:
      - ./:/go/src/app
    ports:
      - 8080:8080
